db_dev:
  database:
    :password: 1901
  secret_key_base: 52e1ae7712b76d320208….


test:
  database:
    :password: 1901
  secret_key_base: b5db85fb51a88...


production:
  database:
    :password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>